export const ShopActionTypes = {
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    SET_CURRENT_PHONE_COLOR: 'SET_CURRENT_PHONE_COLOR',
    SET_CURRENT_TARIFF:'SET_CURRENT_TARIFF',
    SET_CURRENT_CAPACITY: 'SET_CURRENT_CAPACITY',

}